# Generated by Django 5.1.3 on 2024-12-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h3', models.CharField(max_length=1000)),
                ('p', models.CharField(max_length=1000)),
                ('header', models.CharField(max_length=1000)),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
    ]
